#!/bin/bash

if [[ -z "$PYFILE" ]]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi

echo "Compiling $PYFILE ..."
python3 -m compileall -b $PYFILE

if [[ $PYFILE == *.py ]]; then
	output_file=${PYFILE%.*}.pyc
	mv ${PYFILE}c $output_file
fi
